config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get 'health', to: 'health#health'
  resources :categories
  resources :tasks do
    patch :trigger, on: :member
    resources :notes, only: [:create], controller: 'notes'
  end
  root to: 'tasks#index'
end

app/models/category.rb
class Category 
  include Mongoid::Document
  include Mongoid::Timestamps

  field :name, type: String
  field :description, type: String

  has_many :tasks
  validates :name, :description, presence: true
  validates_uniqueness_of :name
end

app/models/note.rb
class Note

  include Mongoid::Document
  include Mongoid::Timestamps

  field :body, type: String

  belongs_to :user
  belongs_to :task

  validates :body, presence: true
end

app/models/participant.rb
class Participant 

  include Mongoid::Document
  include Mongoid::Timestamps

  #enum role: {responsible: 1, follower: 2}

  ROLES = {
    responsible: 1,
    follower: 2
  }

  field :role, type: Integer

  belongs_to :user
  belongs_to :task

  def self.roles 
    ROLES
  end
end

app/models/task.rb
class Task 
  include Mongoid::Document
  include Mongoid::Timestamps
  include Mongoid::Attributes::Dynamic
  include AASM

  field :name, type: String
  field :description, type: String
  field :due_date, type: Date
  field :code, type: String
  field :status, type: String
  field :transitions, type: Array, default: []


  belongs_to :category
  belongs_to :owner, class_name: 'User'
  has_many :participating_users, class_name: 'Participant'
  #has_many :participants, through: :participating_users, source: :user

  has_many :notes

  validates :name, :due_date, :description, presence: true
  validates_uniqueness_of :name
  validate :due_date_validity

  accepts_nested_attributes_for :participating_users, allow_destroy: true

  before_create :create_code
  after_create :send_email

  def participants
    participating_users.includes(:user).map(&:user)
  end

  def due_date_validity
    return if due_date.blank?
    return if due_date > Date.today
    errors.add :due_date, "fecha invalida"
  end

  def create_code
    self.code = "#{owner_id}#{Time.now.to_i.to_s(36)}#{SecureRandom.hex(8)}"
  end

  def send_email
    return unless Rails.env.development?
    #Tasks::SendEmail.new.call self
    Tasks::SendEmailJob.perform_async self.id.to_s
    #Tasks::SendEmailJob.perform_in 5, self.id.to_s
  end

  aasm column: :status, skip_validation_on_save: true do
    state :pending, initial: true
    state :in_process, :finished

    after_all_transitions :audit_status_change

    event :start do
      transitions from: :pending, to: :in_process
    end

    event :finish do
      transitions from: :in_process, to: :finished
    end
  end

  def audit_status_change
    #self.update(transitions: "changing from #{aasm.from_state} to #{aasm.to_state} (event: #{aasm.current_event})")
    set transitions: transitions.push(
      {
        from_state: aasm.from_state,
        to_state: aasm.to_state,
        current_event: aasm.current_event,
        timestamp: Time.zone.now
      }
    )
  end

end

app/models/user.rb
class User 
  include Mongoid::Document
  include Mongoid::Timestamps

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  # field :sign_in_count,      type: Integer, default: 0
  # field :current_sign_in_at, type: Time
  # field :last_sign_in_at,    type: Time
  # field :current_sign_in_ip, type: String
  # field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :owned_tasks, class_name: 'Task'
  has_many :participations, class_name: 'Participant'
  #has_many :tasks, through: :participations

  def tasks
    participations.includes(:task).map(&:task)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  
    def index
      @categories = Category.all
    end

    def new
      @category = Category.new
    end
    
  
    def show
      @category = Category.find(params[:id])
    end
  
    def create
      @category = Category.new(category_params)
      @category.save
      redirect_to categories_path
    end
  
    def update
      @category = Category.find(params[:id])
      @category.update_params(category_params)
      redirect_to categories_path
    end
  
    def edit
      @category = Category.find(params[:id])
    end
  
    def destroy
      @category = Category.find(params[:id])
      @category.destroy

      redirect_to categories_path
    end
    private

    def category_params
      params.require(:category).permit(:name, :description)
    end

end

app/controllers/health_controller.rb
class HealthController < ApplicationController
  def health
    #rails g factory_bot:model user email:string name:string auth:integer 
    @ok = {api: 'OK'}
    render json: @ok, response: :ok
  end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_task

  def create
    @note = Note.new(note_params)
    @note.task = @task
    @note.user = current_user
    @note.save
    render 'tasks/show', task: @note.task
  end

  private

  def note_params
    params.require(:note).permit(:body)
  end

  def set_task
    @task = Task.find(params[:task_id])
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy, :trigger]
  
    def index
      @tasks = (current_user.owned_tasks + current_user.tasks).uniq
    end
  
    def show
    end

    def new
      @task = Task.new
    end

    def create
      @task = Task.new(task_params)
      @task.owner = current_user
      @task.save
      flash[:success] = "Object successfully created"
      #format.html { redirect_to @task, notice: 'Task was successfully created.'}
      #format.json { render :show, status: :created, location: @task }
      redirect_to @task
    end    
  
    def edit
    end

    def update
      @task.update(task_params)
      redirect_to @task
    end
  
    def destroy
      @task.destroy
      redirect_to tasks_path
    end

    def trigger
      Tasks::TriggerEvent.new.call @task, params[:event]
    end

    private

    def task_params
      params.require(:task).permit(:name, :description, :due_date, :category_id, participating_users_attributes: [ :user_id, :role, :id, :_destroy])
    end

    def set_task
      @task = Task.find(params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def available_events_for task
    task.aasm.permitted_transitions.map{|t| t[:event]}
  end
end

app/views/categories/_form.html.erb
<div>
  <%= form_for @category do |f| %>
    <div>
      <%= f.label :name%>
      <%= f.text_field :name  %>
    </div>

    <div>
      <%= f.label :description%>
      <%= f.text_area :description %>
    </div>

    <div>
      <%= f.submit %>
    </div>
  <% end %>
</div>

app/views/categories/edit.html.erb
<%= render 'form'  %>

app/views/categories/index.html.erb
<div>
  <table>
    <thead>
      <tr>
        <th>Nombre</th>
        <th>Descripcion</th>
        <th>Eliminar</th>
      </tr>
    <thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td> <%= link_to category.name, category %> </td>
          <td> <%= category.description %> </td>
          <td> <%= link_to "Eliminar", category, method: :delete, data: { confirm: "r u sure?"} %>
        <tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/categories/new.html.erb
<%= render 'form'  %>

app/views/categories/show.html.erb
<div>
  <%= @category.name %>
  <%= @category.description %>
  <%= link_to 'Tareas', tasks_path%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Organizador</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= link_to "Platzi", root_path%>
      <%= link_to "Categorias", categories_path%>
      <%= link_to "Crear tarea", new_task_path%>
      <%= link_to 'cerrar sesion', destroy_user_session_path, method: :delete %> 
    </header>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/tasks/_form.html.erb
<div>
  <%= form_for @task do |f|%>
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>

    <div>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </div>

    <div>
      <%= f.label :due_date %>
      <%= f.date_field :due_date %>
    </div>

    <div>
      <%= f.label :category_id %>
      <%#= f.number_field :category_id %>
      <%#= f.select :category_id, @categories.inject({}){|item1, item2| item1[item2[:name]] = item2[:id]; item1 } %>
      <%= f.collection_select :category_id, Category.all, :id, :name, {include_blank: true}, {class: "selectize"} %>
    </div>

    <div id="participating-users">
      <%= f.fields_for :participating_users, Participant.new do | p | %>
        <%= render 'participating_user_fields', f: p %>
      <% end %>

      <%= link_to_add_association 'Agregar participante', f, :participating_users %>
    </div>


    
    <div>
      <%= f.submit %>
    </div>

  <% end %>
</div>

<script>
  PLATZI.tasks.form.setup();
</script>

app/views/tasks/_participating_user_fields.html.erb
<div class="nested-fields">
  <div>
    <%= f.label :user_id, 'Usuario' %>
    <%= f.collection_select :user_id, User.all - [current_user], :id, :email, {include_blank: true} ,{class:"selectize user"} %>
  </div>

  <div>
    <%= f.label :role, 'Rol' %>
    <%#= p.select :role, Participant.roles,{include_blank: true}, {class: "selectize"}%>
    <%= f.select :role, Participant.roles, {include_blank: true} ,{class:"selectize role"} %>
  </div>

  
  <div>
    <%= link_to_remove_association "Remover participante", f %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= render 'form'  %>

app/views/tasks/index.html.erb
<div>
  <h1>Lista de tareas</h1>
  <p> A continuacion veras toda la lista de tareas creadas y podras crear una nueva tarea, editarla o eliminarla si eres el creador de la misma </p>
  <div>
    <table>
      <tbody>
        <% @tasks.each do |task| %>
          <div>
            <span> Tarea #<%= link_to task.id, task %> <%= task.name %> </span>
            <span> <%= task.description %> </span>
            <span> <%= task.category.name %> </span>
            <span> <%= task.owner.email %> creado el <%= task.created_at.to_formatted_s(:long) %> / Vence <%= task.due_date %> </span>
          </div>
          <div>
            <span> <%= link_to "Editar", edit_task_path(task)%> </span>
            <span> <%= link_to "Eliminar", task, method: :delete, data: { confirm: "r u sure?"} %> </span>
          </div>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<script>
  PLATZI.tasks.index.setup();
</script>

app/views/tasks/new.html.erb
<%= render 'form'  %>

app/views/tasks/show.html.erb
<div>
  <div>
    <p><%= @task.name %></p>
    <p><%= @task.description %></p>
    <p><%= @task.due_date %></p>
    <p><%= @task.category.name %></p>
    <p><%= @task.owner.email %></p>
    <p class="task-status"><%= @task.status %></p>
    <p>
      <% available_events_for(@task).each do |event| %> 
        <%= link_to event, trigger_task_path(@task, event: event, format: :js), remote: true, method: :patch %>
      <% end %>
    </p>
    
  </div>
  <div>
    <% @task.notes.each do |note|%>
      <p><%= note.body %></p>
    <% end %>
  </div>
  <div>
    <%= form_for Note.new, url: task_notes_path(task_id: @task.id) do |f|%>
      <p> 
        <%= f.text_field :body, placeholder: "Agregar nota" %>
      </p>
        <%= f.submit 'Enviar' %>
    <% end %>
  </div>
  <div>
    <%= link_to 'Editar nota', edit_task_path(@task)%>
  </div>
</div>

app/views/tasks/trigger.js.erb
document.querySelector('.task-status').innerHTML = '<%= @task.status %>'